steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'test', '--trigger-http','--set-env-vars','APP_ENV=${_APP_ENV}', '--runtime', 'nodejs10', '--entry-point', 'helloWorld']
